# Font sources to scan and merge
# locales key points to a json mapping locale -> families. Sources without locales treat all fonts as core fonts

win11:
  dir: win11/fonts
  locales: win11/locales.json

macos:
  dir: macos

ubuntu:
  dir: ubuntu
  locales: ubuntu/locales.json

extras:
  dir: extras